name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
    - name: Install dependencies
        run: npm ci --legacy-peer-deps
        with:
          build: npm run test
          browser: chrome
          spec: cypress/integration/examples/BDD/*.feature
